name: "\U0001F4DD YAML Lint CI"

on:
  push:
    branches: [main, "release/*"]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  yamllint:
    uses: N3b3x/hf-general-ci-tools/.github/workflows/ru-yaml-lint.yml@main
    with:
      paths: ".github/workflows/*.yml,**/*.yml,**/*.yaml"
      config_file: "_config/.yamllint"
